# Generated by Django 4.1 on 2022-09-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('fecha_de_partido', models.DateField()),
                ('equipo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Fanatico',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='reservado',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo',
            field=models.CharField(blank=True, default='Argentina', max_length=100, null=True),
        ),
    ]
